### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by raymer** [lssinc/voyage-app-angular#47]
Write more unit tests to get to 100% coverage. 

Our latest coverage snapshot, generated with `ng test --code-coverage`

![image](https://user-images.githubusercontent.com/490221/42767538-e61459ce-88e2-11e8-9865-5af2e57e47e5.png)

**Comment by roblouie** [comment]
Do we actually want 100% coverage? We definitely don't want to make it so that any time someone modifies Voyage for their project they get failing tests. If there is core functionality that isn't likely to change that is not covered we should cover it, but simply trying to get 100% coverage can easily be counter-productive. Instead I think we need to take a more nuanced approach.

**Comment by raymer** [comment]
I get what you're saying. My concern is a large community of developers that do very much care about coverage and if we don't have it, they will not take the project seriously.
